"""
Plot synthetic FFTSTR benchmark curves.

The synthetic workload is the alternating `abab...` table generated by
`scripts/generate_fftstr_benchmark.py`. It contains one exact no-hit pattern of
length 2, then no-hit underscore-wildcard patterns through length 512.

Usage:
    python3 plots/fftstr_synthetic_plot.py \
        --full-summary path/to/abab_full_summary.csv \
        --fftstr0-summary path/to/abab_fftstr0_summary.csv
"""

from __future__ import annotations

import argparse
import csv
import re
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker


plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["DejaVu Serif"],
    "mathtext.fontset": "cm",
    "font.size": 13,
    "axes.linewidth": 1.2,
})

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_FULL_SUMMARY = (
    PROJECT_ROOT
    / "benchmark_results/fftstr/abab-wildcards/abab_20260609_063058/summary.csv"
)
DEFAULT_OUT_DIR = PROJECT_ROOT / "plots" / "outputs" / "10"

NORMAL_ALGOS = [
    "StdSearch",
    "NaiveVectorizedV2Wildcard",
    "TwoWay",
    "TwoWay2",
    "TwoWay3",
    "PairHorspool",
    "LibcMemmem",
]
FFT_ALGOS = ["FftStr0", "FftStr1", "FftstrV2"]
ALGOS = NORMAL_ALGOS + FFT_ALGOS

COLORS = {
    "StdSearch": "#8d99ae",
    "NaiveVectorizedV2Wildcard": "#2b5d8a",
    "TwoWay": "#79a56f",
    "TwoWay2": "#3f7d5a",
    "TwoWay3": "#73b7a9",
    "PairHorspool": "#7d4e9e",
    "LibcMemmem": "#9b9b9b",
    "FftStr0": "#9a031e",
    "FftStr1": "#d1495b",
    "FftstrV2": "#e8923a",
}
LABELS = {
    "StdSearch": "std search",
    "NaiveVectorizedV2Wildcard": "vectorized wildcard",
    "TwoWay": "TwoWay",
    "TwoWay2": "TwoWay2",
    "TwoWay3": "TwoWay3",
    "PairHorspool": "PairHorspool",
    "LibcMemmem": "libc memmem",
    "FftStr0": "FftStr0 (N/A >42)",
    "FftStr1": "FftStr1",
    "FftstrV2": "FftstrV2",
}
LINESTYLES = {
    "StdSearch": (0, (2, 2)),
    "NaiveVectorizedV2Wildcard": "-",
    "TwoWay": "-",
    "TwoWay2": "-",
    "TwoWay3": (0, (5, 2)),
    "PairHorspool": "-",
    "LibcMemmem": (0, (2, 2)),
    "FftStr0": (0, (1, 1)),
    "FftStr1": "-",
    "FftstrV2": "-",
}

GRID = "#cfcfcf"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--full-summary", type=Path, default=DEFAULT_FULL_SUMMARY)
    parser.add_argument("--fftstr0-summary", type=Path)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    return parser.parse_args()


def pattern_len(name: str) -> int:
    match = re.search(r"len(\d+)", name)
    if not match:
        raise ValueError(f"cannot parse pattern length from {name!r}")
    return int(match.group(1))


def read_summary(path: Path, algos: set[str] | None = None) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    with path.open(newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            algo = row["algorithm"]
            if algos is not None and algo not in algos:
                continue
            if row.get("actual_index") != "full-scan":
                continue
            rows.append({
                "algorithm": algo,
                "pattern_name": row["pattern_name"],
                "length": pattern_len(row["pattern_name"]),
                "query_ms": float(row["geomean_query_total_ns"]) / 1e6,
                "rows_matched": int(row["rows_matched"]),
            })
    return rows


def merge_rows(full_summary: Path, fftstr0_summary: Path | None) -> list[dict[str, object]]:
    rows = read_summary(full_summary, set(NORMAL_ALGOS + ["FftStr1", "FftstrV2"]))
    if fftstr0_summary is not None:
        rows.extend(read_summary(fftstr0_summary, {"FftStr0"}))
    return rows


def plot_curve(rows: list[dict[str, object]], out_dir: Path) -> Path:
    fig, axes = plt.subplots(
        2,
        1,
        figsize=(13.5, 10.4),
        sharey=True,
        gridspec_kw={"height_ratios": [2.0, 1.15], "hspace": 0.28},
    )

    for ax, xmax, title in [
        (axes[0], 512, "Full synthetic range"),
        (axes[1], 64, "Short-pattern zoom"),
    ]:
        for algo in ALGOS:
            cur = sorted(
                (row for row in rows if row["algorithm"] == algo and row["length"] <= xmax),
                key=lambda row: row["length"],
            )
            if not cur:
                continue
            is_fft = algo in FFT_ALGOS
            ax.plot(
                [row["length"] for row in cur],
                [row["query_ms"] for row in cur],
                label=LABELS[algo],
                color=COLORS[algo],
                linestyle=LINESTYLES[algo],
                linewidth=2.8 if is_fft else 1.8,
                alpha=0.98 if is_fft else 0.68,
                marker="o" if is_fft else None,
                markersize=4.2 if is_fft else 0,
                zorder=3 if is_fft else 2,
            )

        ax.axvline(42, color="#666", linewidth=1.0, linestyle=(0, (3, 3)), alpha=0.65)
        ax.text(43.5, 0.006, "FftStr0 max", rotation=90, va="bottom", ha="left", fontsize=9, color="#555")
        ax.set_xlim(2, xmax)
        ax.set_yscale("log")
        ax.grid(True, which="major", axis="y", color=GRID, linewidth=0.8, alpha=0.85)
        ax.grid(True, which="minor", axis="y", color=GRID, linewidth=0.4, alpha=0.35)
        ax.set_title(title, loc="left", fontsize=13)
        ax.set_ylabel("query time (ms)")

    axes[0].set_xticks([2, 64, 128, 192, 256, 320, 384, 448, 512])
    axes[1].set_xticks([2, 3, 4, 8, 16, 24, 32, 40, 48, 56, 64])
    axes[1].set_xlabel("pattern length")

    for ax in axes:
        ax.yaxis.set_major_locator(mticker.LogLocator(base=10, numticks=8))
        ax.yaxis.set_minor_locator(mticker.LogLocator(base=10, subs=range(2, 10), numticks=80))
        ax.yaxis.set_minor_formatter(mticker.NullFormatter())
        ax.yaxis.set_major_formatter(mticker.FuncFormatter(format_ms_tick))

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=5, frameon=False, bbox_to_anchor=(0.5, 0.02))
    fig.suptitle(
        "Synthetic `abab` full scan: normal byte search vs FFTSTR variants",
        y=0.965,
        fontsize=15,
    )
    fig.text(
        0.5,
        0.105,
        "Rows are 1,000 x 512-byte alternating `abab...`; length 2 is exact no-hit, other points are no-hit underscore-wildcard patterns. Y-axis is log scaled.",
        ha="center",
        va="center",
        fontsize=10,
        color="#555",
    )
    fig.subplots_adjust(left=0.085, right=0.985, top=0.91, bottom=0.20, hspace=0.32)

    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "fig_fftstr_synthetic_curve.png"
    fig.savefig(out_path, dpi=220, bbox_inches="tight")
    plt.close(fig)
    return out_path


def format_ms_tick(value: float, _pos: int) -> str:
    if value >= 1:
        return f"{value:g}"
    return f"{value * 1000:g} us"


def main() -> int:
    args = parse_args()
    rows = merge_rows(args.full_summary, args.fftstr0_summary)
    out_path = plot_curve(rows, args.out_dir)
    print(out_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
